def nums(a: str) :
    num = a.count("0")
    print(num)
    num=a.count("1")
    print(num)
    num = a.count("2")
    print(num)
    num = a.count("3")
    print(num)
    num = a.count("4")
    print(num)
    num = a.count("5")
    print(num)
    num = a.count("6")
    print(num)
    num = a.count("7")
    print(num)
    num = a.count("8")
    print(num)
    num = a.count("9")
    print(num)
a="1234567,gegejiushizhandouji.3456789,woyoushuzhinimeiyou."
nums(a)